import type { Metadata } from "next";
import "./globals.css";
import ReactLenis from "lenis/react";
import LenisProvider from "./components/LenisProvider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="en">
      <body
        className="font-courier antialiased w-full overflow-x-hidden">
        <LenisProvider>
          {children}
        </LenisProvider>
          
      </body>
    </html>
  );
}
